### ISSUE TITLE
Calling "mkstemp" without securely setting umask first

### ISSUE THREAD

**Issue by danielwangksu** [ros/rospack#101]
Using mkstemp without setting the permission mask with umask harmful.
https://github.com/ros/rospack/blob/3358d21fbeb5355a459e94354c2aa95e0a376e57/src/rospack.cpp#L2064

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.

**Comment by dirk-thomas** [comment]
Seeing the proposed patch can you clarify why you consider the `mkstemp` call without a `umask` to be *harmful*?

**Comment by danielwangksu** [comment]
The POSIX specification of mkstemp() does not say anything about file modes, although newer version of glibc make file modes changes specifically. It is not necessary, but I think it is probably better for other potential platform to make sure its file mode creation mask (umask(2)) is set appropriately before calling mkstemp() (and mkostemp())

**Comment by dirk-thomas** [comment]
I am trying to understand where do you see writing the file with even 0666 being *harmful*?

**Comment by danielwangksu** [comment]
With 666 any process can read and write to the file. Could be a potential way to inject harmful data
