### ISSUE TITLE
Coverity - TOCTOU time-of-check, time-of-use race condition

### ISSUE THREAD

**Issue by danielwangksu** [ros/rospack#103]
Event fs_check_call: | Calling function "stat" to perform check on "cache_path.c_str()".
https://github.com/ros/rospack/blob/3358d21fbeb5355a459e94354c2aa95e0a376e57/src/rospack.cpp#L2116

Event toctou:	Calling function "fopen" that uses "cache_path.c_str()" after a check function. This can cause a time-of-check, time-of-use race condition.
https://github.com/ros/rospack/blob/3358d21fbeb5355a459e94354c2aa95e0a376e57/src/rospack.cpp#L2116-L2125

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.

**Comment by dirk-thomas** [comment]
Addressed by #104.
