### ISSUE TITLE
rospack cache files created with 000 permissions

### ISSUE THREAD

**Issue by ph1l** [ros/rospack#117]
The permissions on these files make no sense. Why write a file that no one can read?

```
phil@marble-XPS-15-9560:~$ cp -a .ros/ /tmp/ros_backup
cp: cannot open '.ros/rospack_cache_02946445166995464026' for reading: Permission denied
phil@marble-XPS-15-9560:~$ ls -lah .ros/rospack_cache_*
---------- 1 phil phil 6.0K Mar  3 12:07 .ros/rospack_cache_02946445166995464026
```

https://answers.ros.org/question/351675/rospack-cache-files-in-ros-directory-with-no-access-rights/

**Comment by ph1l** [comment]
It looks like the package build for melodic succeeded, but there are no artifacts in jenkins. Anywhere I can d/l then to test?

**Comment by dirk-thomas** [comment]
There are no automatic binary artifacts. The Jenkins build only compiled the package and ran its tests.

**Comment by dirk-thomas** [comment]
Please build the package with your changes from source locally and test that the patch actually adresses the problem (which the first version of the PR doesn't seem to do).

**Comment by ph1l** [comment]
looks like the call to `mkstemp` (https://github.com/ros/rospack/blob/noetic-devel/src/rospack.cpp#L2080) should be creating the cache file, right? Am I misreading the man pages for `mkstemp` and `fdopen`?

**Comment by dirk-thomas** [comment]
This is actually a regression since #106. Without the `umask` calls the file is created with `600` for me.

I am looking into a proper fix...

**Comment by dirk-thomas** [comment]
Please try #119 which should fix the problem.
