### ISSUE TITLE
The name of depends1 command argument is ridiculous

### ISSUE THREAD

**Issue by osandoval** [ros/rospack#16]
I'm a new ROS user, but a programmer for many years, and now that I'm learning ROS I find a command call like:

rospack depends1 .... 

For any user is not obvious that depends1 refers to inmediate dependencies, a different attribute name is required.

**Comment by dirk-thomas** [comment]
The command naming is pretty consistent. `depends1` makes it very clear what the difference to `depends` is but being still very similar. Also the help string describes the meaning very well.

What would be your suggestion instead?

**Comment by osandoval** [comment]
At least for me, the use of `depends1` sounds illogical.

Perhaps if `depends` had a depth parameter, the simplification `depends1` could have more sense.

Maybe, by default, `depends` should represent immediate dependencies, some parameter could represent the depth of the dependencies search, and probably a special call like `deepDepends` or depends with a parameter 0 could represent a complete search.

I'm new in ROS, and I'm not familiar with the source code of its core, but if I can help please tell me.

**Comment by tfoote** [comment]
Thanks for the input.  We can't really reverse logic on a mature product's arguments. And I expect as you become more familiar with the system the current choice of naming will become more natural. If you would like to submit pull requests to improve the documentation and help prompts etc we'd gladly accept them.
