### ISSUE TITLE
rospack should honor CATKIN_IGNORE marker files

### ISSUE THREAD

**Issue by dirk-thomas** [ros/rospack#21]
rospack should ignore all folders containing a CATKIN_IGNORE marker file while crawling for packages.

**Comment by dirk-thomas** [comment]
Based on issue ros/ros#20.

**Comment by meyerj** [comment]
This patch breaks some setups where CATKIN_IGNORE is used to prevent some packages in a workspace to be built, but nevertheless should be found by rospack (and roscd, roslaunch, rosbuild etc. which I assume are using rospack).

There are already several questions with similar problems on ROS answers:
- http://answers.ros.org/question/66508/error-is-not-a-package-or-launch-file-name/
- http://answers.ros.org/question/66515/update-problem-error-is-not-a-package-or-launch-file-name/

Is there another marker file like the former ROS_NOBUILD (or CATKIN_NOBUILD, CATKIN_BLACKLIST) which can be used to blacklist a package during catkin_make but keep it findable by rospack (e.g. containing only launch files, non-catkin packages which contain a package.xml, etc.)?

**Comment by dirk-thomas** [comment]
No, there is no differentiation. Either a package is visible - for build and runtime - or it is ignored. I don't think that it is a good idea to add another marker file which even has different semantic for build and runtime.

The problem described in your referenced questions is all about dry packages where the CATKIN_IGNORE file is generated for an in-source build (which is fixed with the latest version currently in shadow-fixed).

As mentioned in one of the questions you can specify `--pkg` for _catkin_make_ and _catkin_make_isolated_. But this will only give you limited control about which packages to build. If you end up wanting to build only a subset of a workspace but keep all package available at runtime you should really split up the workspace.
