### ISSUE TITLE
Will the rospack c++ API be updated to process catkin tags?

### ISSUE THREAD

**Issue by jbohren** [ros/rospack#22]
I'd like to be able to get a list of run/exec depends from a catkin package.xml, but the rospack c++ API doesn't provide this abstraction. Is the only option to parse the package.xml files manually?

**Comment by dirk-thomas** [comment]
No, rospack only deals with dry packages. Wet packages are only supported to the level which is necessary for backward compatibility. The only API for these information is provided by catkin_pkg (which is Python).

**Comment by jbohren** [comment]
Is there a C++ equivalent for catkin packages?

**Comment by jbohren** [comment]
Ah I see, the _only_ API. Ok.
