### ISSUE TITLE
nao_logger.py  ImportErro: No module named qi

### ISSUE THREAD

**Issue by jwlahey** [ros/rospack#45]
Hey guys, I am trying to connect my nao via remote pc to ros and am running into some issues. It seems that I have my python path set correctly using

export PYTHONPATH=~/pynaoqi/pynaoqi-python-2.7-naoqi-1.14-linux32/:$PYTHONPATH

and when I run individual nodes it seems to connect to them fine except for the nao_logger.py node upon which I receive the following error.

Traceback (most recent call last): File "/opt/ros/hydro/lib/nao_driver/nao_logger.py", line 24, in <module> import qi

does anyone know what is causing this and how to fix it? Thank you so much.

**Comment by dirk-thomas** [comment]
Please use http://answers.ros.org for asking questions as described in http://wiki.ros.org/Support
