### ISSUE TITLE
rosdep non-optional for 'rosdep plugins'

### ISSUE THREAD

**Issue by dgossow** [ros/rospack#5]
I ran into this today after installing groovy on quantal:

The install instructions (http://www.ros.org/wiki/groovy/Installation/Ubuntu) suggest that installing rosdep and rosinstall is optional. However, 'rospack plugins' will not run without running 'rosdep update' first, which will make tools like RViz fail to load.

To reproduce, run 

rm -rf ~/.ros/rosdep
rospack plugins --attrib=plugin rviz

This will give you the error:

[rospack] Error: the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'

Not sure if that should be considered a bug in rospack or if the documentation should just be more explicit about 'sudo rosdep init; rosdep update' being required steps in the installation.

**Comment by mirzashah** [comment]
It's not a bug in rospack. Initializing rosdep is a prerequisite of utilizing ROS and part of the install instructions. We've indicated it on the wiki. In addition rospack + roswtf will also warn you.

That said I'm not certain why this operation isn't automated as a post-install trigger for the .deb....@wjwwood once gave me an explanation but I forget what it was. It bites folks so often that it would be a wise to invest time in figuring out a solution to automate this for users.

**Comment by dgossow** [comment]
From my understanding, the install instructions basically said that rosdep is a useful tool you might want to install if you are compiling ros packages from source, not that it is required to run ROS. It even indicated that you need to install python-rosdep manually if you want to use it, although it is always pulled in by rospack.

I've updated http://www.ros.org/wiki/groovy/Installation/Ubuntu to be more explicit about this.

**Comment by mirzashah** [comment]
Oh awesome, thanks! You're right...we were discussing in our last developer's meeting how these tools somehow got coupled to rosdep. Getting rid of these dependencies on rosdep is one of our goals for hydro+1.
