### ISSUE TITLE
rospack depends geometry_msgs vs rosmsg packages Header

### ISSUE THREAD

**Issue by StephanOpfer** [ros/rospack#6]
Hi,

I am using ROS Fuerte on Ubuntu 12.04 and I have some problem in understanding the consistency of the output of the following two commands:

$rospack depends geometry_msgs:
<nothing>

$rosmsg packages Header
...
gazebo_msgs
gazebo_plugins
geometry_msgs <--
hpPackage
...

So geometry_msgs is using the Header message from std_msgs, but geometry_msgs does not depend on std_msgs. One example of using the Header message is geometry_msgs/TwistStamped:

$rosmsg show geometry_msgs/TwistStamped
std_msgs/Header header <--
  uint32 seq
  time stamp
  string frame_id
geometry_msgs/Twist twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z

Isn't it a bug?

Best Regards, Stephan

p.s.: We had a discussion on answers.ros.org and came to the conclusion, that we should file this issue here. The address to the discussion on answers.ros.org is http://answers.ros.org/question/53333/rospack-depends-geometry_msgs-vs-rosmsg-packages-header

**Comment by dirk-thomas** [comment]
This is less a bug than a design flaw. As pointed out in the wiki in Fuerte the catkinized packages do not have the necessary dependencies stored in their manifest.xml. Instead the dependency information is only available on the stack level. Therefore the output of the commands is not "fixable" in the way you would like them to be.

For Groovy this has been redesigned and therefore the output of the two commands contains the expected information.
