### ISSUE TITLE
New release for kinetic

### ISSUE THREAD

**Issue by concavegit** [ros/rospack#84]
basically #80, but I need rospack on kinetic due to its support for lidar.

**Comment by concavegit** [comment]
Nevremind, a patch was submitted in the ros-overlay.

**Comment by xaedes** [comment]
kinetic is still broken due to this

**Comment by dirk-thomas** [comment]
> kinetic is still broken due to this

Please provide more context. Kinetic targets Ubuntu Xenial which ships with an older Boost version which doesn't have that "problem".

**Comment by xaedes** [comment]
Ah okay thank you, I now understand my problem. It is broken only for my
usecase (xenial with new boost). So never mind.

Am Mi., 31. Okt. 2018 um 17:59 Uhr schrieb Dirk Thomas <
notifications@github.com>:
