### ISSUE TITLE
$rospack find       throws exception error 

### ISSUE THREAD

**Issue by justdoGIT** [ros/rospack#86]
rospack find is giving runtime errors on my beaglebone board. Other rospack commands are running fine like rospack depends.
Here is the screenshot  

![](https://user-images.githubusercontent.com/18480929/34484604-b611f686-efeb-11e7-8621-44a05a6b5f4b.jpg)
and here is the error message : 
debian@beaglebone:~/catkin_ws$ rospack find
terminate called after throwing an instance of 'rospack::Exception'
  what():  error parsing manifest of package class_loader at /home/debian/ros_catkin_ws/install_isolated/share/class_loader/package.xml
Aborted

also after writing $rosrun and pressing tab it is throwing exception error written below :

debian@beaglebone:~/catkin_ws$ rosrun terminate called after throwing an instance of 'rospack::Exception'
  what():  error parsing manifest of package class_loader at /home/debian/ros_catkin_ws/install_isolated/share/class_loader/package.xml

although $ rosrun <pkg_name> <node_name> is running completely fine when typing the whole command without using tab 
with using tab the console is like this ;

debian@beaglebone:~/catkin_ws$ rosrun ros_o3d_wall_f find: '': No such file or directory
o3d-find: '': No such file or directory
find: '': No such file or directory

o3d-pub  o3d-sub  
 
here i pressed tab after $rosrun ros_o3d_wall_f . And then there was this line added "find: no such file or directory" then again i pressed tab and line added was o3d-find: no such file or directory and when i pressed tab for the third time it should me the two nodes o3d -pub and o3d-sub. 
can someone explain me this anomalous behavior. 
i  have installed ros on my board from source files as apt-get repository was unable to find it.

**Comment by dirk-thomas** [comment]
Since the error message mentions a problem parsing the file `/home/debian/ros_catkin_ws/install_isolated/share/class_loader/package.xml` please post the content of that file.

**Comment by dirk-thomas** [comment]
> i have installed ros on my board from source files as apt-get repository was unable to find it.

Without knowing what you have done we can't give you any helpful feedback. Please describe your exact steps / which tutorial you have followed and what happened when it "was unable to find it". Also this question is different from the `rospack` problem and might be better suited for answers.ros.org.

**Comment by dirk-thomas** [comment]
Closing since the same question has been double posted here: https://answers.ros.org/question/278733/rospack-find-throws-exception-error/

Please provide the requested information on answers.ros.org.

**Comment by dirk-thomas** [comment]
See #77.
